version: '3.2'

services:
  portainer:
    image: kibana:6.8.2
    ports:
      - "5601:5601"
    networks:
      - monitor_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  elasticsearch:
    image: elasticsearch:6.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - monitor_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  cadvisor:
    image: google/cadvisor
    restart: always
    volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
    command:   -storage_driver=elasticsearch -storage_driver_es_host="http://elasticsearch:9200"
    deploy:
      mode: global
    networks:
      - monitor_network

networks:
  monitor_network:
    driver: overlay
    attachable: true

volumes:
  esdata: